name: cart service ci

on:
  push:
    branches: ["main"]
    paths:
     - "cart/**"
     - ".github/workflows/actions/action.yaml"
     - ".github/workflows/cart-ci.yaml"
     - "pom.xml"
  pull_request:
    branches: ["main"]
    paths:
     - "cart/**"
     - ".github/workflows/actions/action.yaml"
     - ".github/workflows/cart-ci.yaml"
     - "pom.xml"
  workflow_dispatch:
permissions:
  checks: write
  contents: read
  packages: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main'}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven build command
        run: mvn clean install -pl cart -am
      - name: Run Maven Checkstyle
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        run: mvn checkstyle:check -pl cart -am -Dcheckstyle.output.file=cart-checkstyle-result.xml
      - name: Upload Checkstyle Result
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/cart-checkstyle-result.xml'
      - name: Test Results
        uses: dorny/test-reporter@v1
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' && ( success() || failure()) }}
        with:
          name: Cart-Service-Unit-Test-Results
          path: "cart/**/*-reports/TEST*.xml"
          reporter: java-junit
      - name: OWASP Dependency Check
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'yas'
          path: '.'
          format: 'HTML'
      - name: Upload OWASP Dependency Check Results
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: OWASP-Dependency-Check-Results
          path: $${{github.workspace}}/reports
      # - name: SonarCloud Scan
      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -pl cart -am
      # - name: add coverage report to PR
      #   uses: madrapps/jacoco-report@v1.6.1
      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY:== 'true' }}
      #   with:
      #     paths: ${{github.workspace}}/cart/target/site/jacoco/jacoco.xml
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     min-coverage-overall: 80
      #     min-coverage-changed-files: 60
      #     title: 'Cart Coverage Report'
      #     update-comment: true
      - name: Log in to the Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./cart
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cart-service:latest
        
